### ISSUE TITLE
Make it run in IIS

### ISSUE THREAD

**Issue by danyhoron** [Sicos1977/ChromeHtmlToPdf#1]
Hi,

How can I make it run under IIS?

Thanks.

**Comment by Sicos1977** [comment]
Are you using it from ASP.NET?

**Comment by danyhoron** [comment]
Yes, I'm using ASP.NET.

**Comment by Sicos1977** [comment]
You need to integrate the ChromeHtmlToPdfLib in your application and call that one from code.

**Comment by danyhoron** [comment]
I did, 
```
public static byte[] GeneratePDFUsingChrome(string url)
{
	var filePath = HttpContext.Current?.Server?.MapPath($"~/App_Data/${Guid.NewGuid()}.pdf");
	using (var converter = new Converter(@"c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"))
	{
		converter.ConvertToPdf(new Uri(url), filePath, new PageSettings());
		if (File.Exists(filePath))
		{
			var data = File.ReadAllBytes(filePath);
			File.Delete(filePath);
			return data;
		}
	}

	return null;
}
```
And I got this message: `ChromeHtmlToPdfLib.ChromeException: 'Could not start Chrome'` when it called `.ConvertToPdf`

**Comment by Sicos1977** [comment]
Probably a right issue. Under what user (application pool) is your site running? This user needs enough rights to execute Chrome.exe

**Comment by danyhoron** [comment]
the App Pool is using the `ApplicationPoolIdentity` identity.
I would need this to work in AWS Elastic Beanstalk, and I'm not sure I can change the pool identity there.

**Comment by Sicos1977** [comment]
Well you could try to move Chrome to the same location as where your site is but I am not sure if that will work. The problem is that the ApplicationPoolIdentity is a "user" with low rights.

**Comment by danyhoron** [comment]
I changed the Identity to a user that is in the `Administrators` group and I get the same error.

**Comment by danyhoron** [comment]
I will try to get hold of a portable version of Chrome and embed it w/ my app and see if that works.

**Comment by danyhoron** [comment]
I got it from NuGet.

**Comment by Sicos1977** [comment]
This code is probaby throwing the error so it has something to do with firing up Chrome

`
_chromeProcess = Process.Start(processStartInfo);
if (_chromeProcess == null)
	throw new ChromeException("Could not start Chrome");

_chromeProcess.WaitForInputIdle();

if (_chromeProcess.HasExited)
{
	if (i >= 5)
		throw new ChromeException("Could not start Chrome");

	Thread.Sleep(i * 50);
	i++;
	continue;
}
`

**Comment by Sicos1977** [comment]
Could you otherwise try the code that is on Github, I extended this one with a logstream options so that you can log what is going on inside the converter. I think that the version that is on nuGet does not yet has this option since I'm still developing this version.
```

        /// <summary>
        ///     Creates this object and sets it's needed properties
        /// </summary>
        /// <param name="chromeExeFileName">The full path to the chrome executable</param>
        /// <param name="portRange">
        ///     Force the converter to pick a port from the given range. When not set then the port range 9222
        ///     - 9322 is used
        /// </param>
        /// <param name="userProfile">
        ///     If set then this directory will be used to store a user profile.
        ///     Leave blank or set to <c>null</c> if you want to use the default Chrome userprofile location
        /// </param>
        /// <param name="logStream">When set then logging is written to this stream</param>
        /// <exception cref="FileNotFoundException">Raised when <see cref="chromeExeFileName" /> does not exists</exception>
        /// <exception cref="DirectoryNotFoundException">
        ///     Raised when the <paramref name="userProfile" /> directory is given but
        ///     does not exists
        /// </exception>
        public Converter(string chromeExeFileName, 
                         PortRangeSettings portRange = null,
                         string userProfile = null,
                         Stream logStream = null)
        {
            _logStream = logStream;
```

**Comment by danyhoron** [comment]
I copied a portable version of chrome inside my project and it works.
The issue now is that after each pdf render, I end up w/ 4 orphan Chrome processes.
I'll try to use the command line from C# to generate the PDF.

**Comment by danyhoron** [comment]
Could you add a JavaScript trigger? 
Like WKHtmlToPDF has, when `window.status` is set to a certain value, to trigger the PDF render process.

**Comment by Sicos1977** [comment]
Could you add a JavaScript trigger?
Like WKHtmlToPDF has, when window.status is set to a certain value, to trigger the PDF render process.

I'll to see if that is possible with Chrome... Chrome has a page lifecycle event that can be monitored but I don't know if I can build something around that to trigger PDF generation. It is possible to send javascript code to Chrome but I don't know if that will return something.

**Comment by Sicos1977** [comment]
I added an option to wait for the java-script window.status. Could you try it out and let me know if this works as expected?

```
/// <summary>
///     Converts the given <paramref name="inputUri" /> to PDF
/// </summary>
/// <param name="inputUri">The webpage to convert</param>
/// <param name="outputFile">The output file</param>
/// <param name="pageSettings"><see cref="PageSettings"/></param>
/// <param name="waitForNetworkIdle">Wait until all external sources are loaded</param>
/// <param name="waitForWindowStatus">Wait until the javascript window.status has this value before
///     rendering the PDF</param>
/// <param name="waitForWindowsStatusTimeout"></param>
/// <returns>The filename with full path to the generated PDF</returns>
/// <exception cref="DirectoryNotFoundException"></exception>
public void ConvertToPdf(Uri inputUri, 
						string outputFile, 
						PageSettings pageSettings, 
						bool waitForNetworkIdle,
						string waitForWindowStatus = "",
						int waitForWindowsStatusTimeout = 600000)
```

**Comment by danyhoron** [comment]
I tested it and it waits for status. That's awesome.
Thank you.

**Comment by Sicos1977** [comment]
Perfect
