### ISSUE TITLE
Exception in an event could crash the host application

### ISSUE THREAD

**Issue by Johand86** [Sicos1977/ChromeHtmlToPdf#10]
Hi
Thanks for the great library, but I've stumbled upon an issue that I think you might be interested in looking into.

It seems like any exception raised in the _chromeProcess events (StartChromeHeadless() method - ErrorDataReceived and probably Exited and OutputDataReceived aswell) will cause the host application to terminate unexpectedly. 

Since these are handled synchronously with a ManualResetEvent in the method, I think it would make sense to catch them in the event and rethrow them in the StartChromeHeadless()-method directly. That would allow us to wrap converter.ConvertToPdf in a try-catch and handle the error in the application.

Steps to reproduce:
* Set a breakpoint at the two Environment.Exit lines in Program.cs.
* Throw any exception in _chromeProcess.ErrorDataReceived
* The application will terminate without hitting any of the breakpoints.

This causes an issue when running in a Windows service since it'll shut down the service (and probably restart the application pool for an IIS hosted application).

Best regards
Johan

**Comment by Sicos1977** [comment]
I'm happy to receive a pull request for this issue

**Comment by Sicos1977** [comment]
Implemented with commit da231cafeeeeb1335cb9ac4d702d04e1c70808b5

**Comment by Johand86** [comment]
Awesome, thanks! :)
