### ISSUE TITLE
converting html text takes too long

### ISSUE THREAD

**Issue by ahmedzakaria432** [Sicos1977/ChromeHtmlToPdf#102]
iam tying to convert html to pdf and it takes 1 minute to conversion complete
here is my code
`     using (var converter = new Converter())
                {
                    converter.AddChromeArgument("--no-sandbox");
                      using var ms = new MemoryStream();
                  converter.ConvertToPdf(viewAsString,ms,new ChromeHtmlToPdfLib.Settings.
                        PageSettings(ChromeHtmlToPdfLib.Enums.PaperFormat.A4));
                    return ms.ToArray();
                }`
how can i resolve this issue i am on windows os and running this on my local machine using visual studio

**Comment by Sicos1977** [comment]
Is there something inside the html to tries to load something external like images?

**Comment by Sicos1977** [comment]
No response... closed
