### ISSUE TITLE
Questions about other language calls

### ISSUE THREAD

**Issue by nine-city** [Sicos1977/ChromeHtmlToPdf#104]
I am not familiar with C #. If I use Python or C++to implement pdf conversion by calling dll, which dll files are included in the binary compression package.

**Comment by Sicos1977** [comment]
For Python you can use this --> https://github.com/pythonnet/pythonnet

And I have no idea how to call the C# DLL from C++ but you could also always run the console app.

**Comment by nine-city** [comment]
If I am running from the console, I want to enter a url list as an input parameter. How can I specify the name of the output pdf.

**Comment by Sicos1977** [comment]
Just run the console without any parameters and it will give a list with all the options.

**Comment by nine-city** [comment]
In addition, you can find the installation path of Google Chrome under the Windows platform in your code, and you can also find it from the following two registry locations. 
HKEY_ LOCAL_ MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe
HKEY_ CURRENT_ USER\Software\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe

**Comment by Sicos1977** [comment]
> In addition, you can find the installation path of Google Chrome under the Windows platform in your code, and you can also find it from the following two registry locations. HKEY_ LOCAL_ MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe HKEY_ CURRENT_ USER\Software\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe

I don't know what you mean with this. There is code already inside the library that automaticly tries to find where Chrome is installed.

**Comment by JulienMaille** [comment]
@nine-city May I ask if you found a way to use this library from c++ code? Thanks a lot
