### ISSUE TITLE
Async methods

### ISSUE THREAD

**Issue by njvsvalhalla** [Sicos1977/ChromeHtmlToPdf#12]
Hey there, PrintToPdf for me constantly ends in a deadlock for me. The way you are calling SendAsync is prone to deadlocks (see [this stackoverflow answer](https://stackoverflow.com/a/39007110)).

Changing it to this fixes the deadlock issue (and making the method async, as well ConvertToPdf async)

`            var result = countdownTimer == null
                ? await _pageConnection.SendAsync(message)
                : await _pageConnection.SendAsync(message).Timeout(countdownTimer.MillisecondsLeft);`

Thanks a ton for this btw! I was getting so frustrated with wkHtmlToPdf with wonky formatting and this solves my issue completely!

Side note, I know you've been working on the library and may not have gotten to it yet - but don't forget to update the 'Converting a file or url from code' section to take into account ConvertUri/Stream and PageSettings!

edit: 
Also, before I forget, HttpUtility I think is only for ASP apps so it wasn't compiling for me - I used 'WebUtility' instead and it worked

**Comment by Sicos1977** [comment]
Do you  mean like this?

`        internal async Task<PrintToPdfResponse> PrintToPdf(PageSettings pageSettings, CountdownTimer countdownTimer = null)
        {
            var message = new Message {Method = "Page.printToPDF"};
            message.AddParameter("landscape", pageSettings.Landscape);
            message.AddParameter("displayHeaderFooter", pageSettings.DisplayHeaderFooter);
            message.AddParameter("printBackground", pageSettings.PrintBackground);
            message.AddParameter("scale", pageSettings.Scale);
            message.AddParameter("paperWidth", pageSettings.PaperWidth);
            message.AddParameter("paperHeight", pageSettings.PaperHeight);
            message.AddParameter("marginTop", pageSettings.MarginTop);
            message.AddParameter("marginBottom", pageSettings.MarginBottom);
            message.AddParameter("marginLeft", pageSettings.MarginLeft);
            message.AddParameter("marginRight", pageSettings.MarginRight);
            message.AddParameter("pageRanges", pageSettings.PageRanges ?? string.Empty);
            message.AddParameter("ignoreInvalidPageRanges", pageSettings.IgnoreInvalidPageRanges);
            if (!string.IsNullOrEmpty(pageSettings.HeaderTemplate))
                message.AddParameter("headerTemplate", pageSettings.HeaderTemplate);
            if (!string.IsNullOrEmpty(pageSettings.FooterTemplate))
                message.AddParameter("footerTemplate", pageSettings.FooterTemplate);
            message.AddParameter("preferCSSPageSize", pageSettings.PreferCSSPageSize);

            var result = countdownTimer == null
                ? await _pageConnection.SendAsync(message)
                : await _pageConnection.SendAsync(message).Timeout(countdownTimer.MillisecondsLeft);

            var printToPdfResponse = PrintToPdfResponse.FromJson(result);

            if (string.IsNullOrEmpty(printToPdfResponse.Result?.Data))
                throw new ConversionException("Conversion failed");

            return printToPdfResponse;
        }`

**Comment by njvsvalhalla** [comment]
The first one is correct!

You want to call it with await as well.
```
                using (var memoryStream = new MemoryStream((await _browser.PrintToPdfAsync(pageSettings, countdownTimer)).Bytes))
                {
                    memoryStream.Position = 0;
                    memoryStream.CopyTo(outputStream);
                }
```

And make it async:
```
        public async Task ConvertToPdfAsync(ConvertUri inputUri,
                                 Stream outputStream,
                                 PageSettings pageSettings,
                                 string waitForWindowStatus = "",
                                 int waitForWindowsStatusTimeout = 60000,
                                 int? conversionTimeout = null,
                                 Stream logStream = null)
```

(You don't have to add Async to the method name if you don't want to)

And the other one:
```
        public async Task ConvertToPdfAsync(ConvertUri inputUri,
                          ..........
                await ConvertToPdfAsync(inputUri, memoryStream, pageSettings, waitForWindowStatus,
                    waitForWindowsStatusTimeout, conversionTimeout, logStream);
                          ..........
        }
```

This will change the way end users need to call it, so documentation would go sorta like:

```
                using (var converter = new Converter())
                {
                    await converter.ConvertToPdfAsync(new ConvertUri(url), outputPath, new PageSettings());
                }
```

**Comment by Sicos1977** [comment]
Thanks

**Comment by Sicos1977** [comment]
I changed the code a little bit,

I now use this
`c#                using (var memoryStream = new MemoryStream(_browser.PrintToPdf(pageSettings, countdownTimer).GetAwaiter().GetResult().Bytes))
                {
                    memoryStream.Position = 0;
                    memoryStream.CopyTo(outputStream);
                }
`
