### ISSUE TITLE
Multiple input files

### ISSUE THREAD

**Issue by nicolasr75** [Sicos1977/ChromeHtmlToPdf#13]
Hi,
conversion with a single file works great.
Now I would like to convert multiple html files into a single pdf file. My first question regards the format of --input in case --input-is-list ist set. The documentation for the --input parameter should tell us that it needs to be a file that lists the input files because that wasn't clear to me and I first tried to pass multiple files separated by semicolon/space etc. 

So do I understand it correctly that for multiple input files each file would result in its own pdf file? I am just wondering because as far as I remember, wkhtmltopdf does support combining multiple files into a single pdf. My use case is creating a single pdf report from multiple html files that I generate dynamically.

**Comment by Sicos1977** [comment]
As far as I know this is not possible with Google Chrome. To make something like this I need to use a third party tool. The --input-is-list is used to let ChromeHtmlToPdf know that the input file is a list with files that need to be converted. But if you have 10 input files you get 10 output files.

**Comment by nicolasr75** [comment]
Ok, I will try to merge the created files with PDFSharp then.
Btw, I just noticed you are working on the NetStandard version, Thumbs Up!!!

**Comment by Sicos1977** [comment]
Well the .NETStandard version will take some time. I use methods like accessing the registry and impersonation that is only aviable in Windows.

**Comment by nicolasr75** [comment]
If it helps you, I could try to implement a ChromeFinder that works cross-platform and uses whatever is available (Program Files (x86) or Registry on Windows. There is a tool named ChromeDriver for automatic web app testing which contains code that Google itself uses for finding the Chrome/Chromium exe on various systems. It doesn't even use the registry. That could be used as a start: https://cs.chromium.org/chromium/src/chrome/test/chromedriver/chrome/chrome_finder.cc?q=chrome_finder&sq=package:chromium&dr=C&l=31

**Comment by Sicos1977** [comment]
I'm always open for pull requests :-). I reopened this issue so that we can communicate.

**Comment by Sicos1977** [comment]
Nevermind... I opened a new issue
