### ISSUE TITLE
Valid file extensions

### ISSUE THREAD

**Issue by MKetonen** [Sicos1977/ChromeHtmlToPdf#16]
Hi!

I'm using the version 1.2 of Ur awesome library to convert vector graphics .svg files to .pdf and it works great. But it seems like the new version is not accepting .svg files anymore. By adding the .svg in the code solves the problem:

`switch (ext.ToLowerInvariant())`
`{`
`case ".htm":`
`case ".html":`
`case ".svg":`
`// This is ok`
`break;`
`default:`
` ...`
`}`

It seems the
`PreWrapExtensions.Add(".svg")`
is not working for this file extension at least.

**Comment by Sicos1977** [comment]
It has been added in commit 579d874d46bdd337612dcf88843a246174a8a855
