### ISSUE TITLE
Output file extension

### ISSUE THREAD

**Issue by nicolasr75** [Sicos1977/ChromeHtmlToPdf#17]
I am wondering why in list mode the output file gets the same name as the input file. Shouldn't the extension be changed to ".pdf"? This created some major confusions in my tests because suddenly, without noticing it, the output files became input again...

The relevant code is in Program.cs line 85:

    var outputFile = inputUri.IsFile
                                ? Path.GetFileName(inputUri.AbsolutePath)
                                : FileManager.RemoveInvalidFileNameChars(inputUri.ToString());

**Comment by Sicos1977** [comment]
Yes you are right... that's a bug.

**Comment by Sicos1977** [comment]
Fixed in commit 91ede8f1de50c035bea42e0a4b11215c1af398f6
