### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by nicolasr75** [Sicos1977/ChromeHtmlToPdf#18]
I think there is a bug in line 124 of Program.cs

    using (var output = File.OpenWrite(options.Output))

When using --input-is-list then --output is supposed to be a directory and this cannot be opened for writing. This gets me an "Access denied" exception.

**Comment by sksallaj82** [comment]
You need to have your IDE run as an administrator in order to do what you need. Or, set the folder permissions to allow specific users for writing. And make sure the checkmark on your folder permission for "Read Only" is unchecked.
