### ISSUE TITLE
Binaries for Windows

### ISSUE THREAD

**Issue by PauloFrancaLacerda** [Sicos1977/ChromeHtmlToPdf#19]
Is it possible to download the binaries for Windows?
I'm unable to compile the source-code.
Thanks in advance.

**Comment by Sicos1977** [comment]
Sure.. you can find them here. https://github.com/Sicos1977/ChromeHtmlToPdf/releases/download/1.4/ChromeHtmlToPdf-Windows.zip

**Comment by PauloFrancaLacerda** [comment]
Thanks a lot!
