### ISSUE TITLE
Convert HTML file to PDF

### ISSUE THREAD

**Issue by brunoinds** [Sicos1977/ChromeHtmlToPdf#20]
I was trying to convert to PDF by filePath. But it's not work.

**Comment by Sicos1977** [comment]
Please post a screenshot with the error you are getting.

**Comment by brunoinds** [comment]
![Screen Shot 2019-04-19 at 11 10 10](https://user-images.githubusercontent.com/49789611/56432646-c79a3f00-6293-11e9-91c4-f8c089715401.png)



My code is:
`ChromeHtmlToPdfLib.Converter Renderer = new ChromeHtmlToPdfLib.Converter();
Uri uu = new Uri("file:///C:/Users/freirebruno/Documents/fileHTML.html");
ChromeHtmlToPdfLib.Settings.PageSettings nn = new ChromeHtmlToPdfLib.Settings.PageSettings(Enums.PaperFormat.A4);
Renderer.ConvertToPdf(uu, "C:\Users\freirebruno\Documents\filePDF.pdf", nn, true);
`

**Comment by Sicos1977** [comment]
From where did you get the assembly? Nuget?

**Comment by brunoinds** [comment]
Yes. From Nuget

**Comment by Sicos1977** [comment]
That is a very old one with some bugs in it. Give me 10 minutes and I'll deploy a new version with a lot less bugs :-). Sorry about that... just forgot it to update.

**Comment by brunoinds** [comment]
Yes! Thanks a lot!

**Comment by Sicos1977** [comment]
I just released a new package --> https://www.nuget.org/packages/ChromeHtmlToPdf/1.4.0

It can take some time before it is indexed so give it a few minutes
