### ISSUE TITLE
Allow overriding wrapping of content

### ISSUE THREAD

**Issue by rm3dom** [Sicos1977/ChromeHtmlToPdf#23]
Please see attached patch for allowing unwrapped content. We use this for XML. Regards.

[AllowNoWrapping.zip](https://github.com/Sicos1977/ChromeHtmlToPdf/files/3185158/AllowNoWrapping.zip)

**Comment by Sicos1977** [comment]
I don't understand this solution, do you just want to wrap xml files? Can you give me an example why do did solve it like this?

**Comment by rm3dom** [comment]
First of, thanks for the lib. We do not want to wrap XML. Chrome displays XML just fine, and if the XML has an XSLT attached then Chrome will make use of that. So we do not want to wrap XML.

The solution I am proposing allows you to add additional MIME types, and override/disable the wrapping feature.

**Comment by Sicos1977** [comment]
Can you give me a code example, just for me to better understand it?

**Comment by rm3dom** [comment]
`
            using (var converter = new ChromeHtmlToPdfLib.Converter())
            {
                converter.PreWrapExtensions.Add(new WrapExtension(".xml", false));
                converter.ConvertToPdf(new ConvertUri(infile), outfile, pageSettings);
            }
`

**Comment by rm3dom** [comment]
PreWrapExtensions should probably just be called Extensions and WrapExtension just Extension.

**Comment by rm3dom** [comment]
And then XML with an XSLT is:
```
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="example.xsl"?>
<Article>
  <Title>My Article</Title>
  <Authors>
    <Author>Mr. Foo</Author>
```

**Comment by Sicos1977** [comment]
I still don't understand it... what the difference between

`converter.PreWrapExtensions.Add(new WrapExtension(".xml", false));
`
and just not adding the xml extension to the prewrapextension property.

Because you just check here if the Wrap property is true

`!PreWrapExtensions.Any(wrapExt => wrapExt.Wrap && wrapExt.Extension.Equals(ext, StringComparison.InvariantCultureIgnoreCase)`

**Comment by rm3dom** [comment]
The following tells the Converter to allow `.xml` and **NOT** to wrap the xml:
```csharp
converter.PreWrapExtensions.Add(new WrapExtension(".xml", false)); 
```

The following tells the Converter to allow `.xml` and to wrap the xml:
```csharp
converter.PreWrapExtensions.Add(new WrapExtension(".xml", true)); 
```

In the function, `CheckForPreWrap` , if  `wrapExt.Wrap` is `true` a `PreWrapper` will be created else not. Note that `WrapExtension.Wrap` is by default `true`.
```csharp
if (!PreWrapExtensions.Any(wrapExt => wrapExt.Wrap && wrapExt.Extension.Equals(ext, StringComparison.InvariantCultureIgnoreCase)))
                return false;
```
