### ISSUE TITLE
Support For Local Files (Not Hosted)

### ISSUE THREAD

**Issue by panalgin** [Sicos1977/ChromeHtmlToPdf#24]
Hi,

Going to give it a try but wondered if this could work for a simple "index.html"file present on the local hard disk. So instead of using a hosted web page, either under a www. domain or simply on a local web server, does this support the local html files? It was not stated in the readme so maybe it would be better to mention it there too,

Great work ! Thanks

**Comment by Sicos1977** [comment]
Yes it does

**Comment by panalgin** [comment]
Thanks a lot !
