### ISSUE TITLE
Unable to resolve WebSocketSharp dependency

### ISSUE THREAD

**Issue by gwayx105** [Sicos1977/ChromeHtmlToPdf#26]
Install-Package : Unable to resolve dependency 'WebSocketSharp'. Source(s) used: 'nuget.org', 'Microsoft Visual Studio Offline Packages'.
Anyway solution for this is highly appreciated.

**Comment by doghappy** [comment]
Same issue. 

![image](https://user-images.githubusercontent.com/20038914/67538970-57251c80-f713-11e9-9d7c-bccf0829619d.png)

**Comment by doghappy** [comment]
@gwayx105 I found the reason. You need to install `WebSocketSharp` first, **make sure checked include prerelease**. After that, install `ChromeHtmlToPdf`.
