### ISSUE TITLE
IIS: Chrome exited unexpectedly, One or more arguments are invalid

### ISSUE THREAD

**Issue by AndersRisager** [Sicos1977/ChromeHtmlToPdf#27]
Hi

I am trying to get this running in the IIS but am stuck with this error:
Chrome exited unexpectedly, One or more arguments are invalid (Exception from HRESULT: 0x80000003)

I have tried to place the ChromePortable in the following locations:
- Root of WebApp
- WebAppBin\Bin

I have tried to copy the entire folder "GoogleChromePortable" to those two locations, and to copy the entire content of the "GoogleChromePortable" folder to the two locations. Same error in alle scenarios.

Would it be possible for you to either add a path for the ChromePortable as a parameter or check for a specific path before trying to spin of ChromePortable. If the files is not found at the location, you could throw an error that could point the developer in the error direction.

Extra details:
   at ChromeHtmlToPdfLib.Converter.StartChromeHeadless() in C:\tfs\ChromeHtmlToPdf\ChromeHtmlToPdfLib\Converter.cs:line 380
   at ChromeHtmlToPdfLib.Converter.ConvertToPdf(ConvertUri inputUri, Stream outputStream, PageSettings pageSettings, String waitForWindowStatus, Int32 waitForWindowsStatusTimeout, Nullable`1 conversionTimeout, Nullable`1 mediaLoadTimeout, Stream logStream) in C:\tfs\ChromeHtmlToPdf\ChromeHtmlToPdfLib\Converter.cs:line 983
   at HtmlToPdfApi.Controllers.HtmlToPdfController.PostConvertHtmlToPdf(ConversionRequest req) in c:\Projekter\documendo\Tools\HtmlToPdfApi\Controllers\HtmlToPdfController.cs:line 109

**Comment by AndersRisager** [comment]
Hi Sicos

I saw you added the label "Enhancement", i thought that this project enabled Headless Chrome to run in the IIS?

Have a great day.

Best regards
Anders

**Comment by Sicos1977** [comment]
The code should run just fine when started from IIS, I do the same overhere without any problems.

**Comment by AndersRisager** [comment]
Are you using a Visual studio project when you run it like that?  If so would it be possible for me to see this solution including the Chrome Portable?

I forgot about the enhancement suggestion, that would really help regarding the debugging ; )

**Comment by AndersRisager** [comment]
I have reduced the bug to "Access is Denied", when i added a path to ChromePortable, but here i am stuck. If you add a simple MVC project to your solution, it could show how this could work out of the box - That would be a big help for all trying to get this to work.

I used your solution and added a simple MVC project, and referenced ChromeHtmlToPdfLib directly to start debugging. If you don't add a path and have Chrome installed on your pc, it will default to that directory. If you don't have it installed i think it will just fail and won't look for the path within your app.

I am running:
- VS 2017 - Administrator mode
-  Windows 10
- IIS ver. 10.0.18362.1
- AppPool - Running under ApplicationPoolIdenty

To test it when I start my MVC app, my HomeController looks like this. 
public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";
            var settings = new ChromeHtmlToPdfLib.Settings.PageSettings{};

            var convertUri = new ConvertUri("http://www.google.nl");
            var stream = new System.IO.MemoryStream();

            var chromeExePath = System.AppDomain.CurrentDomain.BaseDirectory + "GoogleChromePortable\\GoogleChromePortable.exe";

            using (var converter = new Converter(chromeExePath))
            {
                converter.ConvertToPdf(convertUri, stream, settings);
            }

            return View();
        }
    }

**Comment by AndersRisager** [comment]
Hi 

Could you please alaborate on the reason for closing this issue?

Best Regards
Anders

**Comment by seanjbsol** [comment]
Hi, I ran in to the same issue, I've found the workaround here

https://stackoverflow.com/questions/56076068/headless-chrome-fails-under-iis-but-works-on-command-line/56076069#56076069?newreg=025b7cefbb8c47d4a928eebbf7348e54

**Comment by Sicos1977** [comment]
You can set the directory with the constructor on the converter class

```csharp
        /// <summary>
        ///     Creates this object and sets it's needed properties
        /// </summary>
        /// <param name="chromeExeFileName">When set then this has to be tThe full path to the chrome executable.
        ///      When not set then then the converter tries to find Chrome.exe by first looking in the path
        ///      where this library exists. After that it tries to find it by looking into the registry</param>
        /// <param name="userProfile">
        ///     If set then this directory will be used to store a user profile.
        ///     Leave blank or set to <c>null</c> if you want to use the default Chrome user profile location
        /// </param>
        /// <param name="logStream">When set then logging is written to this stream for all conversions. If
        /// you want a separate log for each conversion then set the log stream on one of the ConvertToPdf" methods</param>
        /// <exception cref="FileNotFoundException">Raised when <see cref="chromeExeFileName" /> does not exists</exception>
        /// <exception cref="DirectoryNotFoundException">
        ///     Raised when the <paramref name="userProfile" /> directory is given but
        ///     does not exists
        /// </exception>
        public Converter(string chromeExeFileName = null,
                         string userProfile = null,
                         Stream logStream = null)
        {
            _preWrapExtensions = new List<string>();
            _logStream = logStream;

            ResetArguments();

            if (string.IsNullOrWhiteSpace(chromeExeFileName))
                chromeExeFileName = ChromeFinder.Find();

            if (!File.Exists(chromeExeFileName))
                throw new FileNotFoundException("Could not find chrome.exe");

            _chromeExeFileName = chromeExeFileName;

            if (string.IsNullOrWhiteSpace(userProfile)) return;
            var userProfileDirectory = new DirectoryInfo(userProfile);
            if (!userProfileDirectory.Exists)
                throw new DirectoryNotFoundException(
                    $"The directory '{userProfileDirectory.FullName}' does not exists");

            SetDefaultArgument("--user-data-dir", $"\"{userProfileDirectory.FullName}\"");
        }
```
