### ISSUE TITLE
Nuget: install-package : Unable to resolve dependency 'WebSocketSharp'. Source(s) used: 'Nuget'

### ISSUE THREAD

**Issue by AndersRisager** [Sicos1977/ChromeHtmlToPdf#28]
Hi 

I tried adding the package on a fresh MVC solution with .net 4.6.2 on VS 2017 and i got the following error:
install-package : Unable to resolve dependency 'WebSocketSharp'. Source(s) used: 'Nuget', 'Microsoft Visual Studio Offline Packages'.

I got the excapt same error using VS 2019.

A workaround is to first install WebSockedSharp through Package Console:
Install-Package WebSocketSharp -Version 1.0.3-rc11

Then run the following through the console or through the nuget manager:
install-package chromehtmltopdf

Btw. the documentation states dependencies against .NETFramework 4.6.1, but you are actually using .NETFramework 4.6.2 ;)

**Comment by Sicos1977** [comment]
I will check the package for the dependency, where did you read 4.6.1?

**Comment by AndersRisager** [comment]
If you go to the nuget package:
https://www.nuget.org/packages/ChromeHtmlToPdf/

And open dependencies, it states:
.NETFramework 4.6.1

**Comment by Sicos1977** [comment]
That is resolved in the latest nuget packages release. It is using a different package. WebSocketSharp-standard instead of WebSocketSharp
