### ISSUE TITLE
Add delay option

### ISSUE THREAD

**Issue by ramonbrbs** [Sicos1977/ChromeHtmlToPdf#30]
Sometimes we need to export charts and other information with javascript and use a delay to await some loadings in page.

**Comment by Sicos1977** [comment]
You can use wait for window.status for that

```c#
        /// <summary>
        ///     Wait for the javascript window.status to equal the given string before starting PDF conversion
        /// </summary>
        [Option("wait-for-window-status", Required = false, Default = "",
            HelpText = "Wait for the javascript window.status to equal the given string before starting PDF conversion")]
        public string WaitForWindowStatus { get; set; }
```

**Comment by daniherculano84** [comment]
Hello!

Looking for a specific delay in millis without depending on the window status of external html web pages, which window status is always empty. Any option to achieve this?
Thanks!
