### ISSUE TITLE
When the url returns a 500 error code, I do not want to generate a PDF file

### ISSUE THREAD

**Issue by 22140505** [Sicos1977/ChromeHtmlToPdf#31]
I don't want a PDF file that might display as an error message.
Thank you, It's a great project

**Comment by sksallaj82** [comment]
That should be beyond the scope of this project. The fix is actually in your hands.

Before generating a PDF call, you can check the status codes of the URL you're trying to hit:

    HttpClient client = new HttpClient();
    var response = await client.GetAsync(url);
    If (response.IsSuccessStatusCode)
    {
        <generate the pdf code here>
    }
    else 
    {
        <your code here>
    }

**Comment by 22140505** [comment]
It's a solution, but the problem is that not every url returns an error, and my url takes a long time to respond.

**Comment by Sicos1977** [comment]
With this commit an ChromNavigationException is raised when an error occurs when navigating to a page in Chrome
