### ISSUE TITLE
 Support HTML conversion image

### ISSUE THREAD

**Issue by tkggusraqk** [Sicos1977/ChromeHtmlToPdf#34]

**Comment by Sicos1977** [comment]
?

**Comment by Sicos1977** [comment]
For the next time... please post your issues in English

**Comment by Sicos1977** [comment]
I'll put it on my todo list

**Comment by alexhorner** [comment]
+1 on this one. There doesn't appear to be _any_ good cross platform library capable of converting HTML5 to a PNG with transparency etc

**Comment by Sicos1977** [comment]
As of version 2.4.0 it is also possible to convert a webpage to image (PNG) format

**Comment by Sicos1977** [comment]
https://www.nuget.org/packages/ChromeHtmlToPdf/2.4.0
