### ISSUE TITLE
Chrome Portable - "Chrome exited unexpectedly"

### ISSUE THREAD

**Issue by NatsuDragonEye** [Sicos1977/ChromeHtmlToPdf#35]
I downloaded the chrome portable from [chrome portable site](https://www.chrome-portable.com/) (both version 32bit and 64bits). I placed the extracted folder on solution folder and give the path to the converter and always get the message "Chrome exited unexpectedly".

If, from my console application try to start the process (chromeportable.exe) it's open the chrome. Additionally, if I don't send anything on Converter constructor, it works fine and use the chrome installed on my machine.

Can you help understanding what's is being missed when using chrome portable?

I'm using the last version (2.0.6).

**Comment by Sicos1977** [comment]
How are you running the code. Are you running it from the console app or are you using the chromehtmltopdf assembly?

**Comment by NatsuDragonEye** [comment]
I'm running from chromehtmltopdf assembly. I install it throught nugget.

**Comment by Sicos1977** [comment]
Under what user are you running your website in IIS?

**Comment by NatsuDragonEye** [comment]
I'm running under an administrator user. The chrome portable are under my user to avoid permission issues.

**Comment by Sicos1977** [comment]
I've seen this kind of errors happen when the user did not have enough rights. Try to give the user full rights and then see if it works. If so then try to figure out what the needed rights are to get things running
