### ISSUE TITLE
Samples to use in MVC C# ASP.NET

### ISSUE THREAD

**Issue by ironman1964** [Sicos1977/ChromeHtmlToPdf#37]
Hi Kees,

Do you have a sample to render a MVC page to PDF?
I have troubles using wkhtmltopdf and a page that is using jquery scripting ...

Thanks.
Joop

**Comment by Sicos1977** [comment]
No I don't, but you can just open your page on chrome. If it works there than it will also work with my library since it also uses chrome

**Comment by ironman1964** [comment]
I tried it, but it's not going to work... my system uses authentication ...
Starting a page in a new "browser" won't work or can I pass credentials/cookies into the new chrome instance ?

**Comment by Sicos1977** [comment]
If you can set them with javascript then you can.

**Comment by Sicos1977** [comment]
There seems to be an option in the Chrome devtools to set cookies but that is not something that I have implemented at the moment.

https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setCookie

**Comment by Sicos1977** [comment]
No response in 16 days.... closed
