### ISSUE TITLE
Unable to resolve dependency 'FSharp.Compiler.Service.MSBuild.v12.0'

### ISSUE THREAD

**Issue by wccdmorgan** [Sicos1977/ChromeHtmlToPdf#38]

**Comment by Sicos1977** [comment]
?  Wrong project?

**Comment by wccdmorgan** [comment]
Yes, I’m sorry; had multiple tabs open and posted in the wrong project. I didn’t see a delete button so I closed it.

**Comment by Sicos1977** [comment]
No problems... Don't think there is an option in GitHub to delete an issue
