### ISSUE TITLE
Can the conversion be faster?

### ISSUE THREAD

**Issue by 22140505** [Sicos1977/ChromeHtmlToPdf#40]
I found that every time I convert a pdf, Chrome will be launched. So when I have a lot of conversions, the efficiency is relatively low. Is there a way to reuse Chrome that has been started?

**Comment by Sicos1977** [comment]
Can you show me your code, because it is also possible to start chrome once and do all your conversions afterwards

**Comment by 22140505** [comment]
My previous code was simply calling the command line. Just now I looked at the source code and used
ConvertToPdf() can start Chrome only once, thank you
