### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by kfossum** [Sicos1977/ChromeHtmlToPdf#42]
Hi Kees,

tried installing version 211 today; get A fatal error occurred. Running Win2016, Command line: The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [C:\Chrome
HtmlToPdf\].

Any tips? Thx!

best regards Kjetil

**Comment by kfossum** [comment]
Oooops... I had not installed .NET 3.0 from MS... done 👍

**Comment by ivanjaros** [comment]
Same problem when i download the zip version. This should be included in releases.
