### ISSUE TITLE
Have no response when using in a winform button-click event

### ISSUE THREAD

**Issue by pupymk1** [Sicos1977/ChromeHtmlToPdf#43]
I try to put the converter.ConvertToPdf method in a winform button-click event,but it just keeps running and having no response.

here's my code:

`

private void button_Click(object sender, EventArgs e)
        {
           ChromeHtmlToPdfLib.Settings.PageSettings pageSettings = new ChromeHtmlToPdfLib.Settings.PageSettings();

            using (var converter = new Converter())
            {
                converter.ConvertToPdf(new ConvertUri("https://starbounder.org/Starbound_Wiki"), @"d:\starbound.pdf", pageSettings);
            }
        }

`

I have to use the third param in converter.ConvertToPdf(only 2 used in README.md),otherwise it won't work. 
The method works successfully when using in a console APP.But another story in winform.

**Comment by pupymk1** [comment]
It finally worked after i chose to run the method in a thread.
Sooooooooo,case cloesd i gusses?

And i want to say i really appreciate the contributors developing this project.It works much better than the other libs i found.

oh ,don't forget the README.md might needs some little changes.

**Comment by Sicos1977** [comment]
Thanks and what needs to be changed in the README?

**Comment by pupymk1** [comment]
> Thanks and what needs to be changed in the README?

The demo code in section 'Converting a file or url from code'. 
My program failed to overload the ConvertToPdf method with just 2 string params. Maybe it works differently between compilers. BTW Mine is the latest VS on Win10.
