### ISSUE TITLE
Stripped down version of Chrome portable?

### ISSUE THREAD

**Issue by JulienMaille** [Sicos1977/ChromeHtmlToPdf#46]
I'm trying to find a better solution than wkHtmlToPdf on Windows.
I gave ChromeHtmlToPdf a try and it output pdf nicely, but I need a solution when Chrome is not installed on the computer.
Hence I was wondering where you suggest to grab a portable Chrome and if such a setup can be stripped down in order to remove anything that doesn't have to do with html rendering?

Thanks in advance

**Comment by Sicos1977** [comment]
I have no idea, what is the exact problem? The size all together?

**Comment by JulienMaille** [comment]
Yes, the point was to keep it as small as possible

**Comment by Sicos1977** [comment]
I don't think you can get Chrome any smaller. The only option I can think off is to use Chromium but that is not small either and has nog dev interface that you can use to talk to.

**Comment by Sicos1977** [comment]
Chrome portable will also work

**Comment by Kim-SSi** [comment]
For people looking for a good build of chrome that is smallish to use.
I use the ungoogled-chromium version of chromium.
[ungoogled-chromium binaries](https://ungoogled-software.github.io/ungoogled-chromium-binaries/)
