### ISSUE TITLE
Not able to find the pre complied binaries for MacOS and Linux

### ISSUE THREAD

**Issue by Jianpeng-Xu** [Sicos1977/ChromeHtmlToPdf#47]
README.md mentioned 
```
Pre compiled binaries
You can find pre compiled binaries for Windows, Unix and macOS over here

https://github.com/Sicos1977/ChromeHtmlToPdf/releases/download/2.0.11/ChromeHtmlToPdf_211.zip https://github.com/Sicos1977/ChromeHtmlToPdf/releases/download/2.1.6/ChromeHtmlToPdf_216.zip

```

but I was not able to find them from these two links. Any ideas? Thanks.

JX

**Comment by Sicos1977** [comment]
No, the links seem to work fine overhere.

https://github.com/Sicos1977/ChromeHtmlToPdf/releases/download/2.0.11/ChromeHtmlToPdf_211.zip
https://github.com/Sicos1977/ChromeHtmlToPdf/releases/download/2.1.6/ChromeHtmlToPdf_216.zip

![image](https://user-images.githubusercontent.com/6692947/103409096-74e6e080-4b65-11eb-9590-da304aa41d38.png)

You could try the releases page --> https://github.com/Sicos1977/ChromeHtmlToPdf/releases/tag/2.1.6
That is where the above links are pointing to.

![image](https://user-images.githubusercontent.com/6692947/103409133-9d6eda80-4b65-11eb-8439-8d0214414094.png)

**Comment by Jianpeng-Xu** [comment]
Thanks @Sicos1977 for your response. I was able to download the zip files from your link. My issue was that I was not able to find the compiled binaries for Mac and Unix version. Can you elaborate which files are the binaries? I did figured out the binary file for windows as it ends with .exe..

**Comment by piromanneo** [comment]
Same problem here, as I see it, zip contains visual studio dll, exe files... I tried both versions (both links)...

This are the contents:

<img width="292" alt="image" src="https://user-images.githubusercontent.com/9727248/103539024-99a9c380-4e97-11eb-8def-f03914f11543.png">
No idea where to find Unix, macOS prebuild files..

**Comment by Sicos1977** [comment]
That are all the files visual studio produced so I assumed that all file systems were included. I don't have any experiences with macOS singe I don't have an Apple machine

**Comment by lerni** [comment]
The issue remains. I also cannot figure out how these files are supposed to work on Linux or OSX, as the [README](https://github.com/Sicos1977/ChromiumHtmlToPdf#pre-compiled-binaries) states. I would appreciate it, if anybody could shed some light on whether or how this should work, or what's needed to actually do so. Maybe it would be worth reopening the issue, so it’s more likely somebody with the knowledge stumbles over it?
