### ISSUE TITLE
Hanging upon generation

### ISSUE THREAD

**Issue by petermendres** [Sicos1977/ChromeHtmlToPdf#5]
Hello!
I'm trying to run the CMD through code (because for some reason, using the code in the example hangs up on me without any error).

Basically running it via
`           Process p = new Process();`
`            p.StartInfo.UseShellExecute = false;`
`            p.StartInfo.RedirectStandardOutput = true;`
`            p.StartInfo.RedirectStandardError = true;`
`            p.StartInfo.RedirectStandardInput = true;`
`            p.EnableRaisingEvents = true;`
`            p.StartInfo.FileName = @"C:\Windows\system32\cmd.exe";`
`            p.StartInfo.Arguments = $@"/c C:\Users\<path>\ChromeHtmlToPdf --input https://www.google.com/ --output {pdfOutput}";`
`p.Start();`
`            p.BeginErrorReadLine();`
`            p.WaitForExit();`

where `pdfOutput` is basically a path pointing to where "testPdf.pdf" would be, and it just hangs up when I try to run it. 
What's weird is that it works perfectly if I just run it straight from the CMD, I'm not really getting any error on the Process itself.

**Comment by petermendres** [comment]
I don't believe so, I'm testing this on my local and I did make sure to set the Identity I'm using in IIS is set as an Administrator.

**Comment by Sicos1977** [comment]
There was someone else that also had problems using Chrome from IIS. This person solved it by using Chrome Portable.

**Comment by petermendres** [comment]
I took some time to attach a debugger into the solution just to see where it breaks on my end and I got to this error. 

![image](https://user-images.githubusercontent.com/33822661/45225259-b2693500-b2ee-11e8-8007-a48981c6a108.png)

Btw, I'm on .NET Framework 4.5 so I had to downgrade the target framework from 4.6, rebuild, then get the class files in the bin.

**Comment by Sicos1977** [comment]
Sorry for the late response but I had some internet connection problems. I'll try to reproduce the problem on my site and see if I can find why you are getting the Aborted state

**Comment by petermendres** [comment]
If it helps, for some odd reason, the times it switches to Aborted isn't too consistent. Like I get the file created, but at 0kb so I assume the generation failed midway. I've read somewhere that it might be my internet connection that's causing the issue, but that wouldn't really make sense because using the CMD works well for me. If only I could run the cmd through code, maybe that would be a better workaround for my issue :(

**Comment by Sicos1977** [comment]
I just checked in some sourcecode. I switched to another websocket, it seems there is a nasty bug in the standard websocket component that gives the aborted error.

**Comment by petermendres** [comment]
![image](https://user-images.githubusercontent.com/33822661/45279623-4f50eb80-b504-11e8-8146-8367ad2199c3.png)
Unfortunately :(

**Comment by Sicos1977** [comment]
I just published a new release that should solve this problem
