### ISSUE TITLE
Margin is cutting off content

### ISSUE THREAD

**Issue by Tywele** [Sicos1977/ChromeHtmlToPdf#51]
When I use the margins in the PageSettings like this:

```
converter.ConvertToPdf(new ConvertUri(_pathManager.PrintFile), output.OutputFilePath,
                            new PageSettings
                            {
                                PrintBackground = true,
                                MarginBottom        = document.Margin.Bottom,
                                MarginLeft          = document.Margin.Left,
                                MarginRight         = document.Margin.Right,
                                MarginTop           = document.Margin.Top
                            });
```

The content of the page is being cut off on the right side and if I increase the margins on the other sides they are also cutting off content. Like this:

![grafik](https://user-images.githubusercontent.com/8156875/110110700-8344b900-7daf-11eb-946f-801a5a2954de.png)
![grafik](https://user-images.githubusercontent.com/8156875/110101047-6904de00-7da3-11eb-9cd3-7ed00e981b44.png)

Everything else is working like it should as far as I can tell.

**Comment by Sicos1977** [comment]
I don't know why that happen. This code should calculate the new width and height.

```c#
                var maxWidth = (pageSettings.PaperWidth - pageSettings.MarginLeft - pageSettings.MarginRight) * 96.0;
                var maxHeight = (pageSettings.PaperHeight - pageSettings.MarginTop - pageSettings.MarginBottom) * 96.0;
```

Is it possible to post the file that you are converting so that I can have a look into it this weekend?

**Comment by Tywele** [comment]
Yes I can do that give me a moment since I have to censor some stuff on it.

**Comment by Sicos1977** [comment]
You can also sent it to sicos2002@hotmail.com if you don't want to put it on GitHub.

**Comment by Tywele** [comment]
Sent it to you

**Comment by Tywele** [comment]
Got an error sending it to you so I will upload it here. 
[ChromeHtmlToPdfMarginBug.zip](https://github.com/Sicos1977/ChromeHtmlToPdf/files/6090380/ChromeHtmlToPdfMarginBug.zip)

**Comment by Sicos1977** [comment]
I just checked my code and everything is working as expected. It looks like a bug in Chrome. When you open the page and press ctrl + p to save the page as pdf and you change the left page margin then everything is moved to the right. If you change the right page margin then information is cut of. I think your best option is to use the scale option.

![image](https://user-images.githubusercontent.com/6692947/110159510-17804180-7deb-11eb-96f0-dfc27af455d7.png)
