### ISSUE TITLE
Using --user on Linux

### ISSUE THREAD

**Issue by nicolasr75** [Sicos1977/ChromeHtmlToPdf#52]
Hey Kees,

great to see that ChromeHtmlToPdf now works on Linux.
There is one thing that does not currently work on Linux: running as a different user.

The problem is that your current code also looks for a domain to fill ProcessStartupInfo.
But accessing the Domain property of ProcessStartupInfo throws an exception. The 
same goes for the Password and LoadUserProfile. You can see that here. Both getter and setter throw!
https://github.com/eerhardt/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessStartInfo.Unix.cs

Could you pack Domain, Password and LoadUserProfile into an environment check to only evaluate it on Windows?

Then I could still use the UserName field on Linux.

Nicolas

**Comment by Sicos1977** [comment]
Sure will do that, I'll try to add it this week.

**Comment by Sicos1977** [comment]
If I look at the link then username also does not seem to be supported on Linux

**Comment by Sicos1977** [comment]
Is this what you want? --> https://github.com/Sicos1977/ChromeHtmlToPdf/commit/f60092fc7967f6f6f414c474fd79377edd1a67ae

**Comment by nicolasr75** [comment]
Sorry, the link I posted was old and not from the offical repo. This should be up-to-date:
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/ProcessStartInfo.Unix.cs

As you can see, setting the username does not throw an exception anymore. So, pack Password, Domain and LoadUserProfile in an environment check but not Username, then it should be good.

**Comment by Sicos1977** [comment]
So this is what you need on Linux? --> https://github.com/Sicos1977/ChromeHtmlToPdf/commit/878d8d31355c4741b24ad38cd9846e5099cb7611

**Comment by Sicos1977** [comment]
If it's not to much to ask could you make a short tutorial about how you are using (or setup) ChromeHtmlToPdf on Linux so that I can add this to a Wiki page for other people

**Comment by nicolasr75** [comment]
Sorry, I think there is still a thing missing. If my username does not contain a backslash, it does not get assigned to ProcessStartInfo.
It should be

    if (_userName.Contains("\\"))
    {
        userName = _userName.Split('\\')[1];
        domain = _userName.Split('\\')[0];
    }
    else
    {
        userName = _userName;
    }

I promise I will learn how to do pull requests for the next time ;-)
Regarding a Wiki page: yes, I'll try to write something down for Linux.

Thanks for looking into this.
Nicolas

**Comment by Sicos1977** [comment]
You are right, I totaly missed that one

3c51355d1bfa59faa89f20869d51cdff8d2dfecb

**Comment by Sicos1977** [comment]
Doing pulll requests is easy;

- First clone the repo
- Make your own changes in you copy
- Commit your changes
- Make a pull request

**Comment by Sicos1977** [comment]
I also need to fix another bug before I release a new nuget package, I will keep you informed in this issue.

**Comment by Sicos1977** [comment]
https://www.nuget.org/packages/ChromeHtmlToPdf/2.3.0
