### ISSUE TITLE
Run Chrome with --no-sandbox (Linux only?)

### ISSUE THREAD

**Issue by nicolasr75** [Sicos1977/ChromeHtmlToPdf#53]
There is another thing for (at least) Linux. I have a web app that allows the user to create PDF reports that are created via ChromeHtmlToPdf from dynamically created HTML files. Chrome doesn't like to be started headless from the root account without the --no-sandbox argument.

I've seen that you had it in the default arguments, probably for testing, but now it is commented out. Any chance to bring it back via an argument to ChromeHtmlToPdf?

I recompiled the code to include it for a test and with --no-sandbox my web app is able to create the reports. Without it, no chance :-( Background is that the web app runs as a daemon with root privileges. I'm not sure if it makes any difference when I use a dedicated account but it would need higher privileges nevertheless. With my regular user account I can of course start ChromeHtmlToPdf manually but that account can not be used for the daemon.

**Comment by Sicos1977** [comment]
It's never good te run without a sandbox, pottentional security risk, but I'll make an option so that you can turn it on or of

**Comment by nicolasr75** [comment]
I know but in this case all html files are generated by the software itself. There is no external code involved.

**Comment by Sicos1977** [comment]
Made setting the arguments public so that you can do whatever you want --> c86fd6b18943f60a27ccb314060fc0e33e445103
