### ISSUE TITLE
Make the Converter take an ILogger interface instead of a plain stream, at least as an alternative

### ISSUE THREAD

**Issue by EraYaN** [Sicos1977/ChromeHtmlToPdf#54]
The plain stream makes it needlessly difficult to have the library integrate with logging systems like Serilog or the Microsoft.Extensions.Logging pipelines.

**Comment by Sicos1977** [comment]
Merged and I will make this the default instead of the log stream

**Comment by Sicos1977** [comment]
The ILogger interface has now been fully implemented; https://www.nuget.org/packages/ChromeHtmlToPdf/2.5.0
