### ISSUE TITLE
The directory 'd:\ff' does not exists

### ISSUE THREAD

**Issue by southernsun** [Sicos1977/ChromeHtmlToPdf#6]
C:\Projects\ChromeHtmlToPdf_v1.2>ChromeHtmlToPdf.exe version
ChromeHtmlToPdf 1.2.0.0
Copyright c 2017 - Kees van Spelde

running it

C:\Projects\ChromeHtmlToPdf_v1.2>ChromeHtmlToPdf.exe --input result.htm --output result.pdf
2018-11-27T00:19:49 - Stopping Chrome
2018-11-27T00:19:49 - The directory 'd:\ff' does not exists
2018-11-27T00:19:49 - Stopping Chrome

there seems to be some hardcoded reference to d:\ff in the release that is available from GitHub. I will download the source code and give that a try.

**Comment by Sicos1977** [comment]
It seems to be a leftover from some testing that I did... sorry about that. I'll make a release soon so that that is gone.

**Comment by southernsun** [comment]
Thanks for your quick response. No worries, i got the latest source code release and used that. Works like a charm, although i'm running into a CSS bug from Chrome :-) Thanks for making this.
