### ISSUE TITLE
It looks like the background property is not working at all.

### ISSUE THREAD

**Issue by dzida94** [Sicos1977/ChromeHtmlToPdf#60]
I have Tried both entering html with css classes that have set background and entering url to page which has background set and neither option worked

Example:
https://www.w3schools.com/cssref/css_colors.asp
[Test.pdf](https://github.com/Sicos1977/ChromeHtmlToPdf/files/7694398/Test.pdf)

**Comment by Sicos1977** [comment]
Did you enable that you want backgrounds?

**Comment by Sicos1977** [comment]
https://github.com/Sicos1977/ChromeHtmlToPdf/blob/master/ChromeHtmlToPdfLib/Browser.cs#L534

**Comment by dzida94** [comment]
Thank you for such a quick reply. I can't believe I haven't noticed this field before. now works fine.
