### ISSUE TITLE
Failed to install in netcoreapp 2.2

### ISSUE THREAD

**Issue by Nongzhsh** [Sicos1977/ChromeHtmlToPdf#62]
It doesn't support netcoreapp2.2.

**Comment by Sicos1977** [comment]
Are you talking about the console app or the library?

**Comment by Nongzhsh** [comment]
Thank you for your reply.
The **ChromeHtmlToPdfLib** library doesn't support netcoreapp2.2. 
I set "Microsoft.Extensions.Logging.Abstractions"  version to "5.0.0"  and it work nice in  netcoreapp2.2.
