### ISSUE TITLE
Fill form fields

### ISSUE THREAD

**Issue by delasource** [Sicos1977/ChromeHtmlToPdf#68]
In pdf you can define fields that are fillable by the user (viewer). 

It would be nice, to pre-set the content of fillable fields (html form-inputs) via c# code. I previously used IronPdf where this was possible by 

```csharp
// Set content
pdf.Form.GetFieldByName("firstname1").Value = user.Firstname;
// ...

// Set font
const FontTypes fontType = FontTypes.TimesItalic;
const double    fontSize = 10D;
pdf.Form.GetFieldByName("firstname1").SetFont(fontType, fontSize);
// ...
```

Yet the fields are still editable in the viewer app.

**Comment by Sicos1977** [comment]
Sorry but at the moment this is not possible. I'm always open for pull requests.

**Comment by CardenInsurance** [comment]
People from the puppeteer project also had this [request](https://github.com/puppeteer/puppeteer/issues/3646), and they posted this [link ](https://bugs.chromium.org/p/chromium/issues/detail?id=1024713)to the upstream request in the Chromium project.  Chromium says they WontFix that issue, so it would be up to these downstream projects to receive the PDF from Chrome and then edit it to convert the fields to AcroForms.

**Comment by delasource** [comment]
"buggy" is an understatement. It just lacks essential JS and CSS features. Which is why i switched to IronPdf and then to this library with Chrome. I'll probably check out Prince, which is expensive as hell but at least seems to provide the functionality

**Comment by Germs2004** [comment]
> "buggy" is an understatement. It just lacks essential JS and CSS features.

I had CSS working in wkhtmltopdf when I tried it.  The [unfixed](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3025) [bug ](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4713) that made me give up on it was that the AcroForms only work when viewed in Chrome, not Acrobat Reader or other browsers, unless you manually edit the resulting PDF with a hex editor.

**Comment by Sicos1977** [comment]
> "buggy" is an understatement. It just lacks essential JS and CSS features. Which is why i switched to IronPdf and then to this library with Chrome. I'll probably check out Prince, which is expensive as hell but at least seems to provide the functionality

That is also the reason why I made this library, I have used wkHtmlToPdf for years but it lacks all kind of things I needed.
