### ISSUE TITLE
The font changes when converting HTML to PDF

### ISSUE THREAD

**Issue by mbpframework** [Sicos1977/ChromeHtmlToPdf#69]
The font changes when converting HTML to PDF.
here is my code:
```
using (var converter = new Converter())
            {
                ConvertUri convertUri = new ConvertUri("http://localhost:82/%E6%8A%A5%E5%91%8A%E9%A2%84%E8%A7%88.html");
                converter.CaptureSnapshot =true;
                converter.ConvertToPdf(convertUri, @"D:\1.pdf", new ChromeHtmlToPdfLib.Settings.PageSettings()
                {
                    PrintBackground = true,
                    PreferCSSPageSize =true,
                    Landscape =true
                });
            }
```
I found that the style of the mhtml file generated using "capturesnapshot = true" is normal

**Comment by Sicos1977** [comment]
I have no idea why it changes, I do nothing with any fonts, How does the HTML look like when you open it in Chrome and save it as PDF/

**Comment by Sicos1977** [comment]
What happens if you use save as in Chrome?

**Comment by Sicos1977** [comment]
No response.... closed

**Comment by mbpframework** [comment]
![image](https://user-images.githubusercontent.com/6149683/164136497-25030b4a-86c1-43c3-bde5-d114e75a2203.png)
