### ISSUE TITLE
Why this error ?

### ISSUE THREAD

**Issue by Olivier-couvez** [Sicos1977/ChromeHtmlToPdf#70]
![image](https://user-images.githubusercontent.com/77056750/163536001-f2b5c919-309b-418d-8210-4ee001761d9b.png)
Ty for your reply

**Comment by Sicos1977** [comment]
En jij verwacht dat ik die taal kan lezen? = You expect me to understand that language?

**Comment by Sicos1977** [comment]
You are probably using the wrong converter object. Use the complete namespace or add a using to your cs file.
