### ISSUE TITLE
![image](https://user-images.githubusercontent.com/6149683/164136497-25030b4a-86c1-43c3-bde5-d114e75a2203.png)

### ISSUE THREAD

**Issue by mbpframework** [Sicos1977/ChromeHtmlToPdf#71]
![image](https://user-images.githubusercontent.com/6149683/164136497-25030b4a-86c1-43c3-bde5-d114e75a2203.png)

_Originally posted by @mbpframework in https://github.com/Sicos1977/ChromeHtmlToPdf/issues/69#issuecomment-1103414204_

**Comment by mbpframework** [comment]
Maybe I know what the problem is。

**Comment by Sicos1977** [comment]
????

**Comment by mbpframework** [comment]
I solved this problem
