### ISSUE TITLE
Some styles are missing

### ISSUE THREAD

**Issue by pilz97** [Sicos1977/ChromeHtmlToPdf#76]
Hi,

first of all thank you for your library.

I noticed that some styles are ignored in the pdf.
For example my HTML contains a part like that:
![image](https://user-images.githubusercontent.com/42172207/172789070-874c87ef-de4a-4983-beca-095ebfecc276.png)

But the PDF looks like:
![image](https://user-images.githubusercontent.com/42172207/172789208-650c5d3c-ebc3-401b-bdc6-ed0a42141fba.png)

Do you have an idea how to solve this?

**Comment by Sicos1977** [comment]
Per default background printing is turned of, I you need it in your case you need to set it to [true](url) in the `PageSettings `object

```c#
        /// <summary>
        ///     Print background graphics. Defaults to false.
        /// </summary>
        public bool PrintBackground { get; set; }
```

It is the 3rd parameter in the ConvertToPdf method

```c#
        public void ConvertToPdf(
            ConvertUri inputUri,
            string outputFile,
            PageSettings pageSettings,
            string waitForWindowStatus = "",
            int waitForWindowsStatusTimeout = 60000,
            int? conversionTimeout = null,
            int? mediaLoadTimeout = null,
            ILogger logger = null)
```
