### ISSUE TITLE
.NET support version

### ISSUE THREAD

**Issue by san59deep** [Sicos1977/ChromeHtmlToPdf#79]
@Sicos1977 we are using .NET version 4.7.3190 and chromehtmltopdf supports only for 3.1.0 version, is there anyways to use the available version for to run chromehtmltopdf?

**Comment by Sicos1977** [comment]
What exactly do you want to do? Use it in another .net version?

**Comment by san59deep** [comment]
![net version](https://user-images.githubusercontent.com/101329210/179149558-4008b4fb-6f78-4be5-8e34-99e43f6d98b2.PNG)


![cmd screen shot](https://user-images.githubusercontent.com/101329210/179149512-97f02ce0-ae19-4d92-83ad-7632e40d25e9.PNG)

**Comment by Sicos1977** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/3.1

**Comment by Sicos1977** [comment]
I also added the information about installing .net core 3.1 to the readme so other people don't make the same mistake.
