### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by nicolasr75** [Sicos1977/ChromeHtmlToPdf#8]
Any plans to make this .NET Core compatible?

Now that we can write cross-platform command line tools, ASP.NET Core web apps and actually UI apps that run everywhere (at least with the help of Avalonia UI), it would be great if ChromeHtmlToPdf would be usable on all platforms. What do you think?

**Comment by Sicos1977** [comment]
That will be possible but is Chrome also aviable on Linux?

**Comment by nicolasr75** [comment]
Hi Kees,

- what tools do you mean?
- regarding Chrome: I have not yet tried it myself but from this link it should be possible https://www.omgubuntu.co.uk/2018/03/how-to-install-google-chrome-on-ubuntu Altough you need Firefox to download it ;-) Until now I have only used Firefox or Chromium (newest Firefox does not run on Raspberry PI). I was asking myself whether Chromium provides the same services?
- there is a port WebSocketSharp.core that is .NET Standard 2.0 compatible. That could work.

I would be more than happy to test it on Debian, Ubuntu and Linux Mate on Raspberry PI! That's all I have available.

Best regards,
Nicolas

**Comment by nicolasr75** [comment]
Some news: 
I can currently not find any release or preview of Chrome for ARM architecture. Although, it seems Microsoft and Google are at least working on a version for Windows on ARM. Nevertheless I use Chromium on a Raspberry with Linux and I have tested the following command line which worked:

`chromium-browser --headless --print-to-pdf=output.pdf http://www.google.com`

which works and gives good results. So I assume Chromium has the same API as Chrome.

I will do tests with Ubuntu/Debian x64 next week but from what I read Chrome is suppored there.

**Comment by nicolasr75** [comment]
I was able to install Chrome v71 on Ubuntu 14.04. The installer showed the following supported systems Debian/Ubuntu/Fedora/openSUSE (at least 64 bit).

So I think it would really be worth trying to port it to .NET Core. 

Just one usage example from my side:
I want to use PDF generation from dynamically created HTML pages in an ASP.NET Core web application. I would prefer to run this web application on Apache or nginx on a Linux Ubuntu or Debian server.

**Comment by Sicos1977** [comment]
I'll try to make a start on porting this weekend, at the moment I'm a little bit busy with helping my parents with some computer problems. So in this case it is family first :-).

**Comment by githubfanster** [comment]
looking forward to this. i too am looking to use this in an ASP.NET Core web application.
thanks!  :-)

**Comment by Sicos1977** [comment]
It is on my todo list, I already did some changes to remove DLLImport so it should not to hard anymore to make it .net core compatible.

**Comment by sksallaj82** [comment]
I was able to do this in about an hour. All the nuget packages has their own upgrades for asp core, or members that had ported it already. I used those new nuget packages and migrated the code to fit the newer versions.

I tested it from the Console app, and even created a web API out of it. What a great library! Lemme see if I can do a pull request.

**Comment by sksallaj82** [comment]
Okie dokes, submitted a pull request. You can test the repo out yourself by checking out the forked code:

https://github.com/sksallaj82/ChromeHtmlToPdf/tree/master/ChromeHtmlToPDFWebApi

**Comment by Sicos1977** [comment]
.NET core is now support, you can find the nuget package overhere -->https://www.nuget.org/packages/ChromeHtmlToPdf/2.0.0

And the console app overhere --> https://github.com/Sicos1977/ChromeHtmlToPdf/releases/download/2.0/ChromeHtmlTopdf.zip
