### ISSUE TITLE
Chrome exited unexpectedly,    at ChromeHtmlToPdfLib.Converter.StartChromeHeadless()

### ISSUE THREAD

**Issue by cd-linxi** [Sicos1977/ChromeHtmlToPdf#80]
![image](https://user-images.githubusercontent.com/18459074/179177781-e6675278-0710-4c31-bb86-51a0119666f9.png)
The local Windows development environment is running properly, and an error is reported when you put it on the Ubuntu20.04 server.  What is the reason for this? 
Dockerfile added content to download and install Chrome. 
![image](https://user-images.githubusercontent.com/18459074/179178342-1d168a5a-93df-45b4-ada0-cb95e3075a53.png)

**Comment by Sicos1977** [comment]
I don't have any experience with using it on Linux. I think the best is to contact @vitovanjak he also got it to run on Linux

See this issue --> https://github.com/Sicos1977/ChromeHtmlToPdf/issues/72

**Comment by vitovanjak** [comment]
Maybe you can post code snippet also so I can check it out

**Comment by cd-linxi** [comment]
![image](https://user-images.githubusercontent.com/18459074/179200430-2f15834c-b161-4c5e-96c8-d53cc9742414.png)

**Comment by vitovanjak** [comment]
Add `converter.AddChromeArgument("--no-sandbox")` and try then

**Comment by cd-linxi** [comment]
![image](https://user-images.githubusercontent.com/18459074/179202679-e0cdc6e2-e4fe-4056-a593-7b7556260e46.png)
Now it's another error. Do you need to add any parameters?

**Comment by vitovanjak** [comment]
Before you post an error at least read it, it is self-explanatory.

It can't find the file you are referring to in the `htmlUrl` variable.

Please post a snippet where you are generating that file and path and saving it...

**Comment by cd-linxi** [comment]
Thank you for your help. @vitovanjak
