### ISSUE TITLE
Installation/First time confusion

### ISSUE THREAD

**Issue by archergod** [Sicos1977/ChromeHtmlToPdf#84]
Description says that it is for replacement of "WKHTMLtoPDF" tool which is standalone EXE and I call that with my HTML and get the output. I know that tool is outdated to modern HTML and I really love to have simple solution like that, But does your tool require to have Chrome installed on Server? I am not sure if we are allowed to do that .. as we have shared hosting, we can put EXE with our solution and run it from command live. So can you please guide how we can do it without running installer for Chrome on server. Like if we chrome.exe in some folder and run directly from there and in future to upgrade we can just replace Chrome.exe with latest version. Please clarify.

**Comment by Sicos1977** [comment]
Chrome is needed that is why it is called ChromeHtmlToPdf. But you can also use Chrome portable (https://portableapps.com/apps/internet/google_chrome_portable) and place that in whatever folder you want.

The only thing you then have to do is tell the tool where it can find chrome if you install it in a non default location.

```c#
        /// <summary>
        ///     The location for Chrome, when not set then the registry is accessed to get the needed information
        /// </summary>
        [Option("chrome-location", Required = false,
            HelpText =
                "The location for Chrome, when not set then this tool first looks inside the folder where " +
                "it is executed from if it can find Chrome.exe (portable) otherwise the registry is accessed " +
                "to get the needed information")]
        public string ChromeLocation { get; set; }
```

For the rest I added almost all options that you also would use from wkHtmlToPdf

**Comment by Sicos1977** [comment]
You can find all the options for the tool here --> https://github.com/Sicos1977/ChromeHtmlToPdf/blob/master/ChromeHtmlToPdfConsole/Options.cs

I don't know if your own tool is written in some kind of programming language but if it is C# then you can also use the ChromeHtmlToPdfLib that you can find on nuget (https://www.nuget.org/packages/ChromeHtmlToPdf)

**Comment by archergod** [comment]
I have tools in PHP and C# both, my question was for Chrome, do we need to have Chrome installed or it is available with package? Sorry cannot test your tool right now, but it certainly looks promising.

**Comment by Sicos1977** [comment]
> I have tools in PHP and C# both, my question was for Chrome, do we need to have Chrome installed or it is available with package? Sorry cannot test your tool right now, but it certainly looks promising.

I know the question is for Chrome... just download Chrome portable and put it somewhere on your server.
