### ISSUE TITLE
wait-for-window-status option

### ISSUE THREAD

**Issue by JarekLisowski** [Sicos1977/ChromeHtmlToPdf#9]
I found interesting feature 'wait-for-window-status' but I can't get it work.  On my web page I need to wait for all content loaded via ajax so I wanted to use 'wait-for-window-status' to wait. I set in javascript: 
window.status = 'report_ready';
and in command line:
 --wait-for-window-status report_ready
but it doesn't recognise it and wait until time out. I use Chrome.  Can you help me.

**Comment by Sicos1977** [comment]
Can you give me a link to the page so that I can debug to see why it does not work or is the page not public?

**Comment by Sicos1977** [comment]
I just did a local test to see if the method works and it seems to be working fine in my case.

This is the test file that I did make

![image](https://user-images.githubusercontent.com/6692947/49695442-6b176c80-fb9b-11e8-85a7-2df3dd0f690d.png)

And the app is detecting the set windowstatus without any problems

![image](https://user-images.githubusercontent.com/6692947/49695439-55a24280-fb9b-11e8-8421-678cd915e4df.png)

**Comment by Sicos1977** [comment]
No response ... closed
