### ISSUE TITLE
How to render HTML to specific Image size?

### ISSUE THREAD

**Issue by daniherculano84** [Sicos1977/ChromeHtmlToPdf#90]
Hi!

I don't find any PageSetting to specify the width and height in pixels to render my HTML. I made a basic test and the Image is converted with HD resolution by default, but I would like it to be in FullHD. Any help or documentation to read?

Thanks.

**Comment by Sicos1977** [comment]
I use the dev protocol to control Chrome, you could look if something is in there to achieve what you want. If it is not there then it is not possible --> https://chromedevtools.github.io/devtools-protocol/

If it is there and you point me in the correct direction then I can look how to implement it.

**Comment by TheAustinG** [comment]
@Sicos1977 
Hello!

This might already be implemented but I found this while browsing through the dev protocol that you linked. 
https://chromedevtools.github.io/devtools-protocol/tot/Page/#type-VisualViewport

Would this allow us to specify the height & width of the image we are trying to convert HTML to?

If there is already a way to specify the size of the target image, please let me know. I've tried setting the `PageSettings.PaperHeight` & `PageSettings.PaperWidth` properties but they do not seem to have an effect on the image size.

**Comment by Sicos1977** [comment]
At the moment only the following methods are implemented;

```csharp
    /// <summary>
    ///     Sets the viewport size to use when converting
    /// </summary>
    /// <remarks>
    ///     This is a one time only default setting which can not be changed when doing multiple conversions.
    ///     Set this before doing any conversions.
    /// </remarks>
    /// <param name="width">The width</param>
    /// <param name="height">The height</param>
    /// <exception cref="ArgumentOutOfRangeException">
    ///     Raised when <paramref name="width" /> or <paramref name="height" /> is smaller then or zero
    /// </exception>
    public void SetWindowSize(int width, int height)

    /// <summary>
    ///     Sets the window size to use when converting
    /// </summary>
    /// <param name="size"></param>
    public void SetWindowSize(WindowSize size)

```
