### ISSUE TITLE
helping you guys integrate within the scoop ecosystem 👍 

### ISSUE THREAD

**Issue by arnos-stuff** [Sicos1977/ChromeHtmlToPdf#92]
Hi everyone,

You've created a wonderful tool, and I was wondering if you've heard of the [scoop package manager](https://scoop.sh/#/) ?

I've successfully created a [basic scoop manifest](https://gist.github.com/arnos-stuff/4f9b2d92d812b25d0ee8335c543cba78) that you can use to install **your app and both its dependencies**.

The following **one-liner** does the job from any powershell :

```powershell
scoop install https://gist.githubusercontent.com/arnos-stuff/4f9b2d92d812b25d0ee8335c543cba78/raw/cfa861ab3078a20c69157ab45daf33f26005fd63/chrome-html-to-pdf.json
```

here's how it looks visually within the powershell:

![image](https://user-images.githubusercontent.com/118028859/209208153-ec61ea5c-33b0-4a17-8ac6-edabaafc592c.png)

I plan on doing the following:
- [x] add this manifest to a scoop bucket so people don't have to use my ugly gist url
- [ ] help you fully integrate scoop into your workflow (to the best of my abilities)

Wish you well, hope this idea feels interesting to you 🤞 😀

**Comment by arnos-stuff** [comment]
Just for your information, I've now [added it to a scoop bucket!](https://github.com/arnos-stuff/arnos-scoop-bucket)

Installing it is just possible using two lines 💯 

```powershell
# add bucket if not already added
scoop bucket add arno
# use it to install
scoop install chrome-html-to-pdf
```

Here's how it looks like:

![image](https://user-images.githubusercontent.com/118028859/209304777-53c8337b-842e-495d-97ef-a82795d7336c.png)

**Comment by Sicos1977** [comment]
Thanks for making this, one thing. It does not use puppeteer under the hood. It uses Chrome DevTools Protocol (https://chromedevtools.github.io/devtools-protocol/). I made the code myself that was needed to automate Chrome. Puppeteer is a simular tool that also uses the devtools but is used to control everything in Chrome. I just use a part.

**Comment by Sicos1977** [comment]
I added your scoop script to the readme

**Comment by arnos-stuff** [comment]
Thanks for this, don't forget the scoop bucket makes it less ugly and adds some cool aliases, I think it's worth a shot 😉
