### ISSUE TITLE
Use js to modify dom before print?

### ISSUE THREAD

**Issue by Aphexus** [Sicos1977/ChromeHtmlToPdf#94]
Is there any way to insert a script in to the html page to modify the dom before printing? I want to remove some junk elements so they do not show up in the pdf. 

Ideally this could be done with a CL switch such as `--include <JS file>` which should embed the file directly so there are no loading issues. Ideally it would also include jQuery.

**Comment by Aphexus** [comment]
I wonder if I can just remove the disable-extensions flag, install tampermonkey to the chrome version and use that?

**Comment by Sicos1977** [comment]
If you don't want a parameter such as disable extensions then you just can use the RemoveChromeArgument method to remove this parameter.

```c#
        #region RemoveChromeArgument
        /// <summary>
        ///     Removes the given <paramref name="argument" /> from <see cref="DefaultChromeArguments" />
        /// </summary>
        /// <param name="argument">The Chrome argument</param>
        // ReSharper disable once UnusedMember.Local
        public void RemoveChromeArgument(string argument)
        {
            if (string.IsNullOrWhiteSpace(argument))
                throw new ArgumentException("Argument is null, empty or white space");

            switch (argument)
            {
                case "--headless":
                    throw new ArgumentException("Can't remove '--headless' argument, this argument is always needed");
              
                case "--no-first-run":
                    throw new ArgumentException("Can't remove '--no-first-run' argument, this argument is always needed");
                
                case "--remote-debugging-port=\"0\"":
                    throw new ArgumentException("Can't remove '---remote-debugging-port=\"0\"' argument, this argument is always needed");
            }

            if (_defaultChromeArgument.Contains(argument))
            {
                _defaultChromeArgument.Remove(argument);
                WriteToLog($"Removed Chrome argument '{argument}'");
            }
        }
        #endregion
```

**Comment by Sicos1977** [comment]
I now use the Runtime.evaluate method to run javascript code... just check this page to see if there is something that fits your need and I can see if I can build in.

https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-evaluate

**Comment by Aphexus** [comment]
Thanks. I got my code by using native javascript instead of jquery. Everything worked fine. Now having to port some more code over that was using jquery but more complex. It's just a pain not being able too get jquery to work as I have to recode everything.

Maybe Page.addScriptToEvaluateOnNewDocument can be used with jquery?

Maybe a simple jquery flag can be used to include the latest? e.g., --jQuery

Would make it much easier. I don't know why jquery isn't working with a direct paste in to the source though. It clearly is executing but something doesn't work. Maybe it is the chrome version I'm using(it is old).
