### ISSUE TITLE
Some large pages seem to lock up ChromeHtmlToPdf

### ISSUE THREAD

**Issue by Aphexus** [Sicos1977/ChromeHtmlToPdf#95]
https://ncatlab.org/nlab/show/science+of+logic
https://ncatlab.org/nlab/show/geometry+of+physics+--+superalgebra

**Comment by Sicos1977** [comment]
That page worked without any problems for me.
[test.pdf](https://github.com/Sicos1977/ChromeHtmlToPdf/files/10328605/test.pdf)
