### ISSUE TITLE
Hello, I want to ask about page breaks

### ISSUE THREAD

**Issue by nine-city** [Sicos1977/ChromeHtmlToPdf#97]
Hello, there is a pagination div in my website, but it seems that the generated pdf is not pagination
There is a pagination separator between div1 and div2, but the generated pdf is not paginated
The HTML structure is as follows
<div>div1</div>
<div style="break-after: page;"></div>
<div>div2</div>

**Comment by Sicos1977** [comment]
I use chrome to convert everything to pdf so when it works in chrome then it also should work with chromehtmltopdf

**Comment by nine-city** [comment]
My Chrome version is 108, Windows 10 system
After testing, using the print provided by Chrome browser can be paginated normally, and the border of the table can be rendered normally, while the generated PDF file and the border of the table can not be displayed on one side. Could you tell me where I did not operate correctly.
![image](https://user-images.githubusercontent.com/20138490/219399813-4278ab59-cebe-47f8-8943-dd9882333541.png)

![image](https://user-images.githubusercontent.com/20138490/219400001-287209e1-d335-48ff-83cd-066bebf72d2c.png)

The first image is a generated PDF, which is not paginated normally. The second picture is a preview of Chrome's own print
In fact, I have added a div with a page in front of the table label of the table, and only added a style="break after: page;"

**Comment by Sicos1977** [comment]
I have no idea what you are doing wrong. What I said before is that this library uses Chrome to convert HTML to PDF so if something does not work correctly then there is nothing I can't do about it when the problem is in Chrome
